services:
  dragon-postgres-db:
    image: postgres:15-alpine
    container_name: dragon-postgres-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin123}
      - POSTGRES_DB=${DB_NAME:-evolutiondb}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - dragon-bot-network

  dragon-redis-cache:
    image: redis:alpine
    container_name: dragon-redis-cache
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./volumes/redis_data:/data
    networks:
      - dragon-bot-network

  dragon-libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: dragon-libretranslate
    restart: always
    env_file:
      - .env
    environment:
      - LT_HOST=0.0.0.0
      - LT_PORT=5000
      - LT_UPDATE_MODELS=true
      - LT_THREADS=4
      - LT_LOAD_ONLY=en,pb,es,fr,de,it
    ports:
      - "${TRANSLATE_PORT:-5000}:5000"
    volumes:
      - ./volumes/libretranslate_data:/app/data
    networks:
      - dragon-bot-network
    
  dragon-minio-storage:
    image: minio/minio:latest
    hostname: dragon-minio-storage
    container_name: dragon-minio-storage
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-admin123}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ./volumes/minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      dragon-bot-network:
        aliases:
          - dragon-minio-storage.local
  
  dragon-evolution-api:
    image: evoapicloud/evolution-api:v2.3.7
    container_name: dragon-evolution-api
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_URL=${SERVER_URL:-http://localhost:8080}

      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql

      - DATABASE_CONNECTION_URI=postgres://${DB_USER:-admin}:${DB_PASSWORD:-admin123}@dragon-postgres-db:5432/${DB_NAME:-evolutiondb}
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_v2

      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=${REDIS_URI:-redis://dragon-redis-cache:6379/0}
      - CACHE_REDIS_PREFIX_KEY=${REDIS_PREFIX_KEY:-dragon_evo_cache_}
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false

      - S3_ENABLED=true
      - S3_ACCESS_KEY=${MINIO_ROOT_USER:-admin}
      - S3_SECRET_KEY=${MINIO_ROOT_PASSWORD:-admin123}
      - S3_BUCKET=${BUCKET_NAME:-dragon-evo-bucket}
      - S3_PORT=${MINIO_PORT:-9000}
      - S3_ENDPOINT=${S3_ENDPOINT_URL:-dragon-minio-storage}
      - S3_USE_SSL=false
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_FORCE_PATH_STYLE=true

      - AUTHENTICATION_API_KEY=${EVO_API_KEY:-dragon}
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/evolution_instances:/evolution/instances
    networks:
      - dragon-bot-network

networks:
  dragon-bot-network:
    name: dragon-bot-network
    driver: bridge